- name: install dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common

- name: add aptkey
  apt_key:
    url: https://download.docker.com/linux/debian/gpg

- name: add repo
  apt_repository: 
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian stretch stable"
    state: present
